### PR TITLE
Ticket1: Change and create files

### PR DESCRIPTION
**Pull request by feb-git-2021**
Changed readme to display server setting
Server.js file created using node and express

### CODE REVIEW

**Review by feb-git-2021 — COMMENTED** [review]
Great job. Go head with the changes done

**Comment by feb-git-2021** [comment]
This is final merge to  base branch from tickect1

**Comment by feb-git-2021** [comment]
Done

**Review by Jyoti-Kamat — COMMENTED** [review]
Great Job

**Pull request closed without merging**
